CREATE TABLE ROLES (
    ROLE_ID NUMBER PRIMARY KEY,
    ROLE_NAME VARCHAR2(20) UNIQUE NOT NULL
);

INSERT INTO ROLES VALUES (1, 'ADMIN');
INSERT INTO ROLES VALUES (2, 'MANAGER');
INSERT INTO ROLES VALUES (3, 'EMPLOYEE');

CREATE TABLE USERS (
    USER_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL,
    ROLE_ID NUMBER NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_ROLE
        FOREIGN KEY (ROLE_ID)
        REFERENCES ROLES(ROLE_ID)
);

CREATE TABLE EMPLOYEE_MANAGER (
    ID NUMBER PRIMARY KEY,
    EMPLOYEE_ID NUMBER NOT NULL,
    MANAGER_ID NUMBER NOT NULL,

    CONSTRAINT FK_EMPLOYEE
        FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES USERS(USER_ID),

    CONSTRAINT FK_MANAGER
        FOREIGN KEY (MANAGER_ID)
        REFERENCES USERS(USER_ID)
);

CREATE TABLE LEAVE_TYPES (
    LEAVE_TYPE_ID NUMBER PRIMARY KEY,
    LEAVE_TYPE_NAME VARCHAR2(50) UNIQUE NOT NULL,
    MAX_DAYS_PER_YEAR NUMBER NOT NULL
);

INSERT INTO LEAVE_TYPES VALUES (1, 'CASUAL LEAVE', 12);
INSERT INTO LEAVE_TYPES VALUES (2, 'SICK LEAVE', 10);
INSERT INTO LEAVE_TYPES VALUES (3, 'EARNED LEAVE', 15);

CREATE TABLE LEAVE_BALANCE (
    BALANCE_ID NUMBER PRIMARY KEY,
    EMPLOYEE_ID NUMBER NOT NULL,
    LEAVE_TYPE_ID NUMBER NOT NULL,
    YEAR NUMBER NOT NULL,
    TOTAL_DAYS NUMBER NOT NULL,
    USED_DAYS NUMBER DEFAULT 0,
    REMAINING_DAYS NUMBER,

    CONSTRAINT FK_BAL_EMPLOYEE
        FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES USERS(USER_ID),

    CONSTRAINT FK_BAL_TYPE
        FOREIGN KEY (LEAVE_TYPE_ID)
        REFERENCES LEAVE_TYPES(LEAVE_TYPE_ID)
);

CREATE TABLE LEAVE_REQUESTS (
    LEAVE_ID NUMBER PRIMARY KEY,
    EMPLOYEE_ID NUMBER NOT NULL,
    LEAVE_TYPE_ID NUMBER NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    REASON VARCHAR2(500),
    STATUS VARCHAR2(20) DEFAULT 'PENDING',
    MANAGER_COMMENT VARCHAR2(500),
    APPLIED_DATE DATE DEFAULT SYSDATE,

    CONSTRAINT FK_REQ_EMPLOYEE
        FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES USERS(USER_ID),

    CONSTRAINT FK_REQ_TYPE
        FOREIGN KEY (LEAVE_TYPE_ID)
        REFERENCES LEAVE_TYPES(LEAVE_TYPE_ID)
);

INSERT INTO USERS VALUES (1,'Admin User','admin@company.com','admin123',1,SYSDATE);
INSERT INTO USERS VALUES (2,'Manager John','manager@company.com','manager123',2,SYSDATE);
INSERT INTO USERS VALUES (3,'Employee Alice','employee@company.com','employee123',3,SYSDATE);

ALTER TABLE LEAVE_BALANCE
ADD CONSTRAINT unique_balance
UNIQUE (EMPLOYEE_ID, LEAVE_TYPE_ID, YEAR);

COMMIT;

UPDATE USERS SET DELETED = 0 WHERE DELETED IS NULL;

ALTER TABLE USERS MODIFY DELETED NUMBER(1) DEFAULT 0 NOT NULL;

COMMIT;